spring:
  application:
    name: moneta2Lezeni

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/ordersdb}
    username: user
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false

  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      group-id: transaction-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "navrat.name.moneta2lezeni.dto"

  redis:
    host: ${SPRING_REDIS_HOST:localhost}

  resilience4j:
    circuitbreaker:
      instances:
        lezeniApi:
          registerHealthIndicator: true
          slidingWindowSize: 10
          minimumNumberOfCalls: 5
          failureRateThreshold: 50
          waitDurationInOpenState: 10000
          permittedNumberOfCallsInHalfOpenState: 3

    ratelimiter:
      instances:
        monetaSync:
          limitForPeriod: 1
          limitRefreshPeriod: 10s
          timeoutDuration: 0

api:
  moneta:
    base-url: https://transparentniucty.moneta.cz/api/v1
    endpoint-statement: /accountDetail
  lezeni:
    base-url: https://lezeni.navrat.name/api/rest
    endpoint-platba: /prezence/platba/{vs}/{amount}